superlemma-list-gui/src/main/java/org/fa/superlemmalist/jsf/LemmaController.java
package org.fa.superlemmalist.jsf;

import java.util.ArrayList;
import java.util.List;
import jakarta.annotation.PostConstruct;
import jakarta.enterprise.context.SessionScoped;
import jakarta.enterprise.inject.Instance;
import jakarta.faces.annotation.ManagedProperty;
import jakarta.inject.Inject;
import jakarta.inject.Named;
import org.fa.superlemmalist.jpa.LanguageVariant;
import org.fa.superlemmalist.jpa.Lemma;
import org.fa.superlemmalist.jpa.Superlemma;
import org.fa.superlemmalist.jsf.converters.LemmaConverter;
import org.fa.superlemmalist.jsf.converters.SuperlemmaConverter;
import org.fa.superlemmalist.jsf.lazy.LazyLemma;
import org.fryske_akademy.jpa.Param;

@SessionScoped
@Named
public class LemmaController extends SuperController<Lemma, LazyLemma> {

    @Override
    protected void fillCopy(Lemma newEntity, Lemma selected) {
        newEntity.setLanguageVariant(selected.getLanguageVariant());
        newEntity.setSuperlemma(selected.getSuperlemma());
    }
    
    private final List<LanguageVariant> languageVariants = new ArrayList<>(10);
    
    @PostConstruct
    private void init() {
        languageVariants.addAll(getCrudReadService().findAll(LanguageVariant.class));
    }
    
    @Inject
    @Named("superlemmaConverter")
    private SuperlemmaConverter superlemmaConverter;

    @Override
    protected void fillNew(Lemma entity) {
        if (getFilterString("superlemma")!=null) {
            entity.setSuperlemma( superlemmaConverter.getAsObject(null, null, getFilterString("superlemma")));
        }
    }

    
    @Override
    public List<String> complete(String query) {
        List<String> l = new ArrayList<>(30);
        getCrudReadService().find("Lemma.likeLemma", Param.one("lemma", query),null, 30, Lemma.class).forEach((h) -> {
            l.add(LemmaConverter.getKey(h));
        });
        return l;
    }
    
    @Override
    public Lemma create(Lemma e) {
        Lemma t = super.create(e);
        getLazyModel().getFilters().put("lemma", t.getLemma());
        return t;
    }

    public List<LanguageVariant> getLanguageVariants() {
        return languageVariants;
    }

    @Inject
    private Instance<SuperlemmaController> superlemmaController;

    public String showSuperlemma(Lemma l) {
        return filterAndRedirect(superlemmaController.get(), "code", l.getSuperlemma().getCode(), "/superlemma/List");
    }


}

superlemma-list-gui/src/main/java/org/fa/superlemmalist/jsf/SuperController.java
package org.fa.superlemmalist.jsf;

import org.fa.superlemmalist.ejb.SuperCrudBean;
import org.fryske_akademy.Util;
import org.fryske_akademy.jpa.AbstractEntity;
import org.fryske_akademy.jsf.NewSupportingLazyController;
import org.fryske_akademy.jsf.lazy.NewSupportingLazyModel;
import org.fryske_akademy.services.CrudReadService;
import org.fryske_akademy.services.CrudWriteService;

import jakarta.enterprise.util.AnnotationLiteral;
import jakarta.faces.context.FacesContext;
import jakarta.inject.Inject;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.HashSet;
import java.util.Set;

public abstract class SuperController<T extends AbstractEntity, R extends NewSupportingLazyModel<T>> extends NewSupportingLazyController<T, R> {


    @Inject
    @SuperCrudBean
    private transient CrudReadService crudReadService;

    @Inject
    private transient CrudWriteService crudWriteService;
    
    private void readObject(ObjectInputStream inputStream) throws IOException, ClassNotFoundException {
        inputStream.defaultReadObject();
        crudWriteService =  Util.getBean(CrudWriteService.class);
        crudReadService = Util.getBean(CrudReadService.class, SUPER_ANNOTATION);
    }
    
    private static class SuperAnnotation extends AnnotationLiteral<SuperCrudBean> implements SuperCrudBean {}
    
    public static final SuperAnnotation SUPER_ANNOTATION = new SuperAnnotation();

    
    @Override
    public CrudReadService getCrudReadService() {
        return crudReadService;
    }

    @Override
    public CrudWriteService getCrudWriteService() {
        return crudWriteService;
    }

    public boolean isRememberTableState() {
        return super.isRememberTableState() && !FILTERING.equals(
                FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get(STATE));
    }
    private Set<String> sortingCols = new HashSet<>(5);

    @Override
    protected String newRowOnLastPage(String table) {
        return "lastPage('" + table + "');";
    }

    @Override
    protected String newRowOnCurrentPage(String table) {
        return "";
    }

    @Override
    public String gotoPageContaining(T entity) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    protected void fillCopy(T newEntity, T selected) {
    }

    @Override
    protected boolean useFilterMechanism() {
        return true;
    }
}

superlemma-list-gui/src/main/webapp/lemma/List.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="Lemma"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <c:set var="ctrl" value="#{lemmaController}"/>
            <c:set var="rowCount" value="#{lazyLemma.rowCount}"/>
            <h:form id="LemmaListForm">
                <ui:include src="/buttons.xhtml">
                    <ui:param name="tabel" value="Lemma"/>
                </ui:include>
                <p:dataTable allowUnsorting="true" id="datalist" value="#{ctrl.lazyModel}" var="item"
                             selection="#{ctrl.selected}" sortMode="multiple" selectionMode="single"
                             paginator="true" editable="#{sessionBean.mayEdit()}" editingRow="#{sessionBean.mayEdit()}"
                             rowKey="#{ctrl.getRowKey(item.id)}" filteredValue="#{lazyLemma.filtered}"
                             rows="#{settings.rowsInTable}" lazy="true" draggableColumns="true" resizableColumns="true" liveResize="true" widgetVar="datalist"
                             rowsPerPageTemplate="10,20,30,40,50" multiViewState="#{ctrl.rememberTableState}"
                             currentPageReportTemplate="{startRecord}-{endRecord} of {totalRecords}"
                             paginatorTemplate="{RowsPerPageDropdown} {CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}">
                    <ui:include src="/datatable.xhtml"/>
                    <p:column sortBy="#{item.lemma}" filterBy="#{item.lemma}" filterValue="#{lazyLemma.filters['lemma']}">
                        <f:facet name="filter">
                            <p:keyboard showMode="button" layoutTemplate="#{ctrl.diacriticsKeyBoard()}" onkeyup="PF('datalist').filter();" 
                                        styleClass="createfilter" value="#{lazyLemma.filters['lemma']}"/>
                        </f:facet>
                        <f:facet name="header">
                            <h:outputText value="lemma"></h:outputText>
                        </f:facet>
                        <p:cellEditor>
                            <f:facet name="output">
                                <h:outputText value="#{item.lemma}"></h:outputText>
                            </f:facet>
                            <f:facet name="input">
                                <p:inputText onchange="changed($(this))" id="lemma" value="#{item.lemma}"  />
                            </f:facet>
                        </p:cellEditor>
                    </p:column>
                    <p:column sortBy="#{item.languageVariant}" filterBy="#{item.languageVariant}" filterValue="#{lazyLemma.filters['languageVariant']}">
                        <f:facet name="filter">
                            <p:selectOneMenu appendTo="datalist"
                                             value="#{lazySuperlemma.filters['languageVariant']}"
                                             onchange="PF('datalist').filter()">
                                <f:selectItem itemLabel="#{bundle.SelectOneMessage}" value="#{null}"></f:selectItem>
                                <f:selectItems value="#{lemmaController.getLanguageVariants()}" var="lv"
                                               itemLabel="#{lv.code}" itemValue="#{lv.code}"></f:selectItems>
                            </p:selectOneMenu>
                        </f:facet>
                        <f:facet name="header">
                            <h:outputText value="languageVariant"></h:outputText>
                        </f:facet>
                        <p:cellEditor>
                            <f:facet name="output">
                                <h:outputText value="#{item.languageVariant}"></h:outputText>
                            </f:facet>
                            <f:facet name="input">
                                <p:selectOneMenu onchange="changed($(this))" id="lv" value="#{item.languageVariant}">
                                    <f:selectItems value="#{ctrl.getLanguageVariants()}" var="lv" itemLabel="#{languageVariantConverter.getAsString(null, null, lv)}" itemValue="#{lv}"/>
                                </p:selectOneMenu>
                            </f:facet>
                        </p:cellEditor>
                    </p:column>
                    <p:column sortBy="#{item.superlemma}" filterBy="#{item.superlemma}" filterValue="#{lazyLemma.filters['superlemma']}">
                        <f:facet name="header">
                            <h:outputText value="superlemma"></h:outputText>
                        </f:facet>
                        <p:cellEditor>
                            <f:facet name="output">
                                <h:outputText value="#{item.superlemma}"></h:outputText>
                            </f:facet>
                            <f:facet name="input">
                                <p:autoComplete onchange="changed($(this))" id="superlemma" value="#{item.superlemma}" completeMethod="#{superlemmaController.complete}"/>
                            </f:facet>
                        </p:cellEditor>
                    </p:column>
                    <p:column >
                        <f:facet name="header">
                            <h:outputText value="link"></h:outputText>
                        </f:facet>
                        <h:outputText value="#{item.getLink()}"></h:outputText>
                    </p:column>
                </p:dataTable>
            </h:form>
        </ui:define>
    </ui:composition>
</html>